package fr.lordfinn.steveparty.entities.custom.magpie;

import fr.lordfinn.steveparty.Steveparty;
import net.minecraft.util.Identifier;

/**
 * The wild Pie's colours (textures generated by the Workshop's build_magpie_variants.py from the classic one): the
 * classic black and white with blue-green wings (the Common pot's Pie's look too), the azure-winged one, the golden
 * (yellow beak, bronze sheen), the rusty, the pale (leucistic) and the dark (melanistic, violet sheen). Which one is
 * born where: {@link WildMagpieSpawns#variantFor}.
 */
public enum MagpieVariant {
    CLASSIC("classic"),
    AZURE("azure"),
    GOLDEN("golden"),
    RUSTY("rusty"),
    PALE("pale"),
    DARK("dark");

    public final String id;
    public final Identifier texture;

    MagpieVariant(String id) {
        this.id = id;
        this.texture = id.equals("classic") ? Steveparty.id("textures/entity/magpie.png")
                : Steveparty.id("textures/entity/magpie/" + id + ".png");
    }

    public static MagpieVariant byId(int ordinal) {
        MagpieVariant[] all = values();
        return ordinal >= 0 && ordinal < all.length ? all[ordinal] : CLASSIC;
    }
}
