"""Generates the SteveParty demo board as a datapack function.

Writes <run-server>/world/datapacks/steveparty-demo/, then in game (or through `.\\scripts\\dev.ps1 cmd`):
    /reload
    /function steveparty_demo:board

The board: a loop of 20 tiles (2 start tiles, 2 blue and 2 red inventory tiles linked to a chest of emeralds,
the rest default tiles), a Party Controller and a Step Controller with levers, two tokens owned by the dev player,
and a kit (dice, wand, token, wrench, cartridges) given to the player.
"""
import json
import os
import sys
import uuid

RUN_DIR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', '..', 'run-server')
PLAYER = 'LordFinn'
Y = 118  # tiles sit on the grass of the flattened area (grass top at y=117)
X0, X1, Z0, Z1, STEP = 314, 326, 426, 434, 2

CHEST = (320, Y, 430)
CONTROLLER = (318, Y, 438)
STEP_CONTROLLER = (322, Y, 438)

WHITE, GOOD, BAD = 0xE8E8E8, 0x0083DF, 0xC41C24


def loop_positions():
    top = [(x, Y, Z0) for x in range(X0, X1 + 1, STEP)]
    right = [(X1, Y, z) for z in range(Z0 + STEP, Z1 + 1, STEP)]
    bottom = [(x, Y, Z1) for x in range(X1 - STEP, X0 - 1, -STEP)]
    left = [(X0, Y, z) for z in range(Z1 - STEP, Z0, -STEP)]
    return top + right + bottom + left


def int_array(u):
    v = uuid.UUID(u).int
    parts = [(v >> s) & 0xFFFFFFFF for s in (96, 64, 32, 0)]
    return '[I;' + ','.join(str(p - (1 << 32) if p >= 1 << 31 else p) for p in parts) + ']'


def dest(pos):
    return '{destinations:[[I;%d,%d,%d]],world:""}' % pos


def cartridge(item, nxt, extra=''):
    return ('{Slot:0b,id:"steveparty:%s",count:1,components:{"steveparty:tile-behavior-component":%s%s}}'
            % (item, dest(nxt), extra))


def main():
    tiles = loop_positions()
    starts = {0, 10}
    blue = {4, 14}
    red = {7, 17}
    offline_uuid = str(uuid.uuid3(uuid.NAMESPACE_DNS, 'x'))  # placeholder, replaced below
    # Offline UUID the dev client joins with (same formula as gradle/dev-server.gradle)
    import hashlib
    md5 = bytearray(hashlib.md5(('OfflinePlayer:' + PLAYER).encode()).digest())
    md5[6] = (md5[6] & 0x0F) | 0x30
    md5[8] = (md5[8] & 0x3F) | 0x80
    offline_uuid = str(uuid.UUID(bytes=bytes(md5)))
    owner = int_array(offline_uuid)

    cmds = ['# SteveParty demo board (generated by scripts/demo-board/build_demo_board.py)',
            'kill @e[type=!minecraft:player,x=305,y=110,z=418,dx=30,dy=20,dz=28]',
            'fill 305 118 418 335 125 446 air',
            'fill 305 117 418 335 117 446 grass_block']

    chest_items = ','.join('{Slot:%db,id:"minecraft:emerald",count:64}' % s for s in range(9))
    cmds.append('setblock %d %d %d minecraft:chest{Items:[%s]}' % (*CHEST, chest_items))

    for i, pos in enumerate(tiles):
        nxt = tiles[(i + 1) % len(tiles)]
        if i in starts:
            state, item = 'tile_start', cartridge('tile_behavior_start', nxt, ',"steveparty:color":%d' % WHITE)
        elif i in blue or i in red:
            negative = i in red
            ghost = '{id:"minecraft:emerald",count:3%s}' % (
                ',components:{"steveparty:is-negative":true}' if negative else '')
            extra = (',"steveparty:inventory-cartridge":{items:[%s]}'
                     ',"steveparty:inventory-pos":[I;%d,%d,%d]'
                     ',"steveparty:selection-state":1'
                     ',"steveparty:color":%d') % (ghost, *CHEST, BAD if negative else GOOD)
            state, item = 'tile_inventory_interactor', cartridge('inventory_cartridge', nxt, extra)
        else:
            state, item = 'default', cartridge('board_space_behavior', nxt, ',"steveparty:color":%d' % WHITE)
        cmds.append('setblock %d %d %d steveparty:tile[tile_type=%s]{Items:[%s]}' % (*pos, state, item))

    cmds += [
        'setblock %d %d %d steveparty:party_controller[facing=north]' % CONTROLLER,
        'setblock %d %d %d minecraft:lever[face=floor,facing=north]' % (CONTROLLER[0] - 1, Y, CONTROLLER[2]),
        'setblock %d %d %d steveparty:step_controller' % STEP_CONTROLLER,
        'setblock %d %d %d minecraft:lever[face=floor,facing=north]' % (STEP_CONTROLLER[0] + 1, Y, STEP_CONTROLLER[2]),
    ]

    for i, (name, color, mob) in zip(sorted(starts), [('Pion rouge', 'red', 'pig'), ('Pion bleu', 'aqua', 'sheep')]):
        x, y, z = tiles[i]
        cmds.append(('summon minecraft:%s %.1f %d %.1f {Tokenized:1b,TokenOwner:%s,PersistenceRequired:1b,'
                     'CustomNameVisible:1b,CustomName:\'{"text":"%s","color":"%s"}\'}')
                    % (mob, x + 0.5, y, z + 0.5, owner, name, color))

    kit = ['steveparty:default_dice', 'steveparty:double_dice', 'steveparty:tokenizer_wand', 'steveparty:token',
           'steveparty:wrench', 'steveparty:board_space_behavior 4', 'steveparty:inventory_cartridge 2',
           'steveparty:tile 8', 'steveparty:mini_games_catalogue']
    cmds += ['give %s %s' % (PLAYER, k) for k in kit]
    cmds += ['tp %s 320.5 %d 440.5 180 20' % (PLAYER, Y),
             'tellraw %s {"text":"[demo] Plateau prêt : levier du Party Controller = lancer la partie, '
             'lance un dé (clic droit) pour jouer. Levier du Step Controller = étape suivante.","color":"gold"}' % PLAYER]

    pack = os.path.join(RUN_DIR, 'world', 'datapacks', 'steveparty-demo')
    fdir = os.path.join(pack, 'data', 'steveparty_demo', 'function')
    os.makedirs(fdir, exist_ok=True)
    with open(os.path.join(pack, 'pack.mcmeta'), 'w', encoding='utf-8') as f:
        json.dump({'pack': {'pack_format': 57, 'description': 'SteveParty demo board'}}, f)
    with open(os.path.join(fdir, 'board.mcfunction'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(cmds) + '\n')
    print('written', os.path.join(fdir, 'board.mcfunction'), len(cmds), 'commands, owner', offline_uuid)


if __name__ == '__main__':
    main()
